"""Add original_filename field to documents table

Revision ID: 7c237c345803
Revises: 386798d9f88d
Create Date: 2025-08-26 12:01:00.694520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c237c345803"
down_revision: Union[str, None] = "386798d9f88d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=False,
            server_default="unnamed_file",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "original_filename")
    # ### end Alembic commands ###
